# Generated by Django 2.1.2 on 2018-11-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class1',
        ),
        migrations.DeleteModel(
            name='Class2',
        ),
    ]
