# Generated by Django 2.1.4 on 2018-12-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20181228_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='resWatsonClase',
        ),
        migrations.RemoveField(
            model_name='document',
            name='resWatsonScore',
        ),
    ]
