# Generated by Django 2.1.4 on 2019-01-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media/contracts/')),
                ('keywords', models.FileField(upload_to='media/keywords/')),
            ],
        ),
    ]
