# Generated by Django 2.1.4 on 2019-01-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20190102_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='keywords',
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonKeywords',
            field=models.FileField(blank=True, null=True, upload_to='keywords'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(upload_to='contracts/'),
        ),
    ]
