# Generated by Django 2.1.4 on 2019-01-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20190102_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(upload_to='analyzer/contracts', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='resWatsonKeywords',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/keywords'),
        ),
    ]
