# Generated by Django 2.1.4 on 2019-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20190102_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='resWatsonCategories',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/categories'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonConcepts',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/concepts'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonEmotions',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/emotions'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonEntities',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/entities'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonRelations',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/relations'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonSemanticRoles',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/semanticRoles'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resWatsonSentiment',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/sentiment'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='resWatsonKeywords',
            field=models.FileField(blank=True, null=True, upload_to='analyzer/results/keywords'),
        ),
    ]
