# Generated by Django 2.1.4 on 2019-01-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_auto_20190107_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='resWatsonEmotions',
        ),
    ]
