# Generated by Django 2.1.4 on 2019-01-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_contract_reswatsoncontractelements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNatureParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureParty', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContractText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contractnatureparty',
            name='contractText',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.ContractText'),
        ),
    ]
