# Generated by Django 2.1.4 on 2019-01-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_auto_20190114_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('contractText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.ContractText')),
            ],
        ),
    ]
